blank_issues_enabled: true
contact_links:
  - name: General Support and Questions
    url: https://github.com/stephenmcd/mezzanine/discussions/new
    about: Ask for help from the Mezzanine community
